// Code generated by goctl. DO NOT EDIT.
package relation

type PageRequest struct {
	Page     int `json:"page"`
	PageSize int `json:"pageSize"`
}

type RelationPageRequest struct {
	PageRequest
	RelationUserId  int    `json:"relationUserId"`
	TransactionType int    `json:"transactionType"`
	RelationTypeId  int    `json:"relationTypeId"`
	StartTime       string `json:"startTime"`
	EndTime         string `json:"endTime"`
	Remark         string  `json:"remark"`
}

type RelationRequest struct {
	RelationID      int       `json:"relationId"`
	RelationUserID  int       `json:"relationUserId"`
	RelationTypeID  int8      `json:"relationTypeId"`
	TransactionType int8      `json:"transactionType"`
	Money           float64    `json:"money"`
	Remark          string    `json:"remark"`
	Date            string    `json:"date"`
	OwnerID         int       `json:"ownerId"`
}
type DeleteRequest struct {
	Ids []int `json:"Ids"`
}

type SystemUserPageRequest struct {
	PageRequest
	Name string  `json:"name"`
	Status   int8 `json:"status"`
}

type RelationUserPageRequest struct {
	PageRequest
	RelationUserId int  `json:"relationUserId"`
	Status         int8 `json:"status"`
}

type RelationUserRequest struct {
	RelationUserID   int    `json:"relationUserId"`
	RelationUserName string `json:"relationUserName"`
	Sex              int8   `json:"sex"`
	Status           int8   `json:"status"`
	Remark           string `json:"remark"`
	OwnerID          int    `json:"ownerId"`
	Search           string `json:"search"`
}

type RelationTypeRequest struct {
	RelationTypeID   int    `json:"relationTypeID"`
	RelationTypeName string `json:"relationTypeName"`
}

type RelationResponse struct {
	Code int    `json:"code"` // 业务码
	Msg  string `json:"msg"`  // 业务消息
}
